version: '3.4'

# networks:
#   myNetwork:
#     driver: bridge

services:

  # bloodbankmanagementdb:
  #   container_name: app-db
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   ports:
  #     - "8002:1433"
  #   environment:
  #     - MSSQL_SA_PASSWORD=Password@123
  #     - ACCEPT_EULA=Y
  #   networks:
  #     - myNetwork

  bloodbankmanagementapi:
    image: ${DOCKER_REGISTRY-}bloodbankmanagementapi
    build:
      context: .
      dockerfile: BloodBankManagement.API\Dockerfile
    ports:
      - 8000:80
      - 8001:81
    depends_on:
      - bloodbankmanagementdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      # - DB_HOST=BloodBankManagement
      # - DB_NAME=BloodBankManagementDB
      # - DB_USER=sa
      # - MSSQL_SA_PASSWORD=Password@123
    # networks:
    #   - myNetwork